# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/users_roaming/vtrolard/dev/perso/login/login_ui.ui'
#
# Created: Tue May  4 16:06:58 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(424, 291)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setMinimumSize(QtCore.QSize(250, 250))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lg_email = QtWidgets.QLineEdit(self.page)
        self.lg_email.setObjectName("lg_email")
        self.verticalLayout_2.addWidget(self.lg_email)
        self.lg_passw = QtWidgets.QLineEdit(self.page)
        self.lg_passw.setObjectName("lg_passw")
        self.verticalLayout_2.addWidget(self.lg_passw)
        self.error = QtWidgets.QLabel(self.page)
        self.error.setMaximumSize(QtCore.QSize(16777215, 15))
        self.error.setText("")
        self.error.setObjectName("error")
        self.verticalLayout_2.addWidget(self.error)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.page)
        self.checkBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.btn_login = QtWidgets.QPushButton(self.page)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_3.addWidget(self.btn_login)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.sign_user = QtWidgets.QLineEdit(self.page_2)
        self.sign_user.setText("")
        self.sign_user.setObjectName("sign_user")
        self.verticalLayout.addWidget(self.sign_user)
        self.sign_email = QtWidgets.QLineEdit(self.page_2)
        self.sign_email.setText("")
        self.sign_email.setObjectName("sign_email")
        self.verticalLayout.addWidget(self.sign_email)
        self.sign_passw = QtWidgets.QLineEdit(self.page_2)
        self.sign_passw.setText("")
        self.sign_passw.setObjectName("sign_passw")
        self.verticalLayout.addWidget(self.sign_passw)
        self.error_2 = QtWidgets.QLabel(self.page_2)
        self.error_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.error_2.setText("")
        self.error_2.setObjectName("error_2")
        self.verticalLayout.addWidget(self.error_2)
        self.btn_sign = QtWidgets.QPushButton(self.page_2)
        self.btn_sign.setObjectName("btn_sign")
        self.verticalLayout.addWidget(self.btn_sign)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_tab = QtWidgets.QPushButton(Dialog)
        self.btn_tab.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btn_tab.setCheckable(True)
        self.btn_tab.setChecked(True)
        self.btn_tab.setObjectName("btn_tab")
        self.horizontalLayout_6.addWidget(self.btn_tab)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Login", None, -1))
        self.lg_email.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Email or Username", None, -1))
        self.lg_passw.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Password", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Remember me", None, -1))
        self.btn_login.setText(QtWidgets.QApplication.translate("Dialog", "Login", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Sign Up", None, -1))
        self.sign_user.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Username", None, -1))
        self.sign_email.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Email", None, -1))
        self.sign_passw.setPlaceholderText(QtWidgets.QApplication.translate("Dialog", "Password", None, -1))
        self.btn_sign.setText(QtWidgets.QApplication.translate("Dialog", "Sign Up", None, -1))
        self.btn_tab.setText(QtWidgets.QApplication.translate("Dialog", "Sign Up", None, -1))

